export const MUNICIPALITIES = [
  'Andrés Bello',
  'Antonio Rómulo Costa',
  'Ayacucho',
  'Bolívar',
  'Cárdenas',
  'Córdoba',
  'Fernández Feo',
  'Francisco de Miranda',
  'García de Hevia',
  'Guásimos',
  'Independencia',
  'Jáuregui',
  'José María Vargas',
  'Junín',
  'Libertad',
  'Libertador',
  'Lobatera',
  'Michelena',
  'Panamericano',
  'Pedro María Ureña',
  'Rafael Urdaneta',
  'Samuel Dario Maldonado',
  'San Cristóbal',
  'San Judas Tadeo',
  'Seboruco',
  'Simón Rodríguez',
  'Sucre',
  'Torbes',
  'Uribante',
];
